/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Live
         * @description Liveness probe: process event loop can respond.
         */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness probe: required dependencies are healthy.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/degraded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Degraded
         * @description Degraded probe: optional dependencies and degradation capability.
         */
        get: operations["health_degraded_health_degraded_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Summary
         * @description Combined health summary.
         */
        get: operations["health_summary_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DependencyHealth
         * @description Health of one external dependency.
         */
        DependencyHealth: {
            /**
             * Name
             * @description Logical dependency name.
             */
            name: string;
            /** @description Current dependency status. */
            status: components["schemas"]["HealthStatus"];
            /**
             * Required
             * @description Whether this dependency is required for the service to be ready.
             */
            required: boolean;
            /**
             * Message
             * @description Human-readable detail.
             */
            message?: string | null;
            /**
             * Latency Ms
             * @description Probe latency in milliseconds if measured.
             */
            latency_ms?: number | null;
        };
        /**
         * HealthProjection
         * @description Unified health projection exposed by /health/* endpoints and consumed by the Web UI.
         *
         *     live:   process event loop can respond.
         *     ready:  all required dependencies are healthy.
         *     degraded: optional dependencies that are unhealthy or operating in degraded mode.
         */
        HealthProjection: {
            /**
             * Service
             * @description Service logical name, e.g. api or web.
             */
            service: string;
            /**
             * Version
             * @description Product version.
             */
            version: string;
            /** @description Process liveness. */
            live: components["schemas"]["HealthStatus"];
            /** @description Readiness for traffic. */
            ready: components["schemas"]["HealthStatus"];
            /** @description Degraded state of optional dependencies. */
            degraded: components["schemas"]["HealthStatus"];
            /**
             * Dependencies
             * @description Per-dependency status.
             */
            dependencies?: components["schemas"]["DependencyHealth"][];
            /**
             * Extensions
             * @description Additional opaque telemetry; UI must not depend on undocumented keys.
             */
            extensions?: {
                [key: string]: unknown;
            };
        };
        /**
         * HealthStatus
         * @description Top-level health verdict.
         * @enum {string}
         */
        HealthStatus: "pass" | "fail" | "unknown";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthProjection"];
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthProjection"];
                };
            };
        };
    };
    health_degraded_health_degraded_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthProjection"];
                };
            };
        };
    };
    health_summary_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthProjection"];
                };
            };
        };
    };
}
